spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0.0"

accounts:
  message: "Welcome to the Accounts Service in QA Environment"
  contactDetails:
    name: "Smithan Kumar - QA Lead"
    email: "Ttqgj@example.com"
  onCallSupport:
    -(555) 555-5555
    -(555) 555-5556